### PR TITLE
Add sniff to require use statements

### PR DESCRIPTION
**Pull request by othercorey**
@ADmad

### CODE REVIEW

**Comment by dereuromark** [comment]
You might want to exclude certain parts here, the downside would be otherwise that any \... const/func would autofix to use statement:

    use const JSON_ERROR_NONE;
    
and we didn't decide yet to spam the use block with also constants, functions and CO :)
For now this should probably be limited to class/interface/trait references only.

**Comment by dereuromark** [comment]
It also blindly converts e.g.

    // @see \...\TransferToEntityMapper::mapEntity()
    
into a use statement, also killing the original docblock..
which is just bonkers, that's a docblock and shouldn't be touched.
So I guess it has some small bugs that also need solving first.

**Comment by othercorey** [comment]
Looks like the slevomat bug was patched. Is this ok now?

**Comment by ADmad** [comment]
Don't want things like `use const JSON_ERROR_NONE;`.

**Comment by othercorey** [comment]
> Don't want things like `use const JSON_ERROR_NONE;`.

I believe that can be disabled with `allowFallbackGlobalConstants`

**Pull request merged**
