### PR TITLE
Allow attribute between docblock and function.

### PR DESCRIPTION
**Pull request by ADmad**
This will prevent errors for code like:

```php
/**
 * docblock
 */
#[ReturnTypeWillChange]
public function foo()
```

### CODE REVIEW

**Comment by othercorey** [comment]
We want to fully copy this instead of pushing the change to phpcs?

**Comment by ADmad** [comment]
> We want to fully copy this instead of pushing the change to phpcs?

The sniff now overrides every method of the parent so I just removed the extension. I have no interest in getting the change done in phpcs itself. My change probably doesn't cover all scenarios and I don't want to spend more time on this.

**Comment by othercorey** [comment]
Yup, I prefer we don't extend it either then.

**Comment by ADmad** [comment]
I had to bump phpcs to latest minor for attributes support. So we'll need a new minor release after merging this.

**Pull request merged**
