### PR TITLE
Include class name sniff.

### PR DESCRIPTION
**Pull request by dereuromark**
Helps to resolve issues about multiple classes per file (https://github.com/cakephp/cakephp/pull/12950) and typos.

    vendor/bin/phpcs --colors -p tests/ --sniffs=CakePHP.Classes.ClassFileName

### CODE REVIEW

**Comment by dereuromark** [comment]
For core to pass the following files would need to be fixed:
```
FILE: cakephp/cakephp/tests/TestCase/Controller/ControllerTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------
 34 | ERROR | Class name doesn't match filename; expected "class ControllerTest"
-------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Controller/Component/PaginatorComponentTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 35 | ERROR | Class name doesn't match filename; expected "class PaginatorComponentTest"
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Controller/Component/RequestHandlerComponentTest.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 33 | ERROR | Class name doesn't match filename; expected "class RequestHandlerComponentTest"
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Controller/Component/SecurityComponentTest.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 33 | ERROR | Class name doesn't match filename; expected "class SecurityComponentTest"
------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Controller/ComponentRegistryTest.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------------
 31 | ERROR | Class name doesn't match filename; expected "class ComponentRegistryTest"
--------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Error/DebuggerTest.php
------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------
 25 | ERROR | Class name doesn't match filename; expected "class DebuggerTest"
------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Error/ExceptionRendererTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------
 51 | ERROR | Class name doesn't match filename; expected "class ExceptionRendererTest"
---------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Console/ShellTest.php
-----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | Class name doesn't match filename; expected "class ShellTest"
-----------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Http/SessionTest.php
----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class SessionTest"
----------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Database/Schema/TableSchemaTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class TableSchemaTest"
-------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Database/ExpressionTypeCastingIntegrationTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | Class name doesn't match filename; expected "class ExpressionTypeCastingIntegrationTest"
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Database/ExpressionTypeCastingTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | Class name doesn't match filename; expected "class ExpressionTypeCastingTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Core/InstanceConfigTraitTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 25 | ERROR | Class name doesn't match filename; expected "class InstanceConfigTraitTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Core/StaticConfigTraitTest.php
--------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------
 23 | ERROR | Class name doesn't match filename; expected "class StaticConfigTraitTest"
--------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Datasource/ConnectionManagerTest.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------------
 18 | ERROR | Class name doesn't match filename; expected "class ConnectionManagerTest"
--------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/TableTest.php
-------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------
 46 | ERROR | Class name doesn't match filename; expected "class TableTest"
-------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/CompositeKeysTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------
 31 | ERROR | Class name doesn't match filename; expected "class CompositeKeysTest"
---------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/BehaviorTest.php
----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------
 24 | ERROR | Class name doesn't match filename; expected "class BehaviorTest"
----------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/Locator/TableLocatorTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 29 | ERROR | Class name doesn't match filename; expected "class TableLocatorTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/Behavior/Translate/TranslateTraitTest.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 22 | ERROR | Class name doesn't match filename; expected "class TranslateTraitTest"
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/Behavior/TranslateBehaviorTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | Class name doesn't match filename; expected "class TranslateBehaviorTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/Behavior/TranslateBehaviorShadowTableTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 29 | ERROR | Class name doesn't match filename; expected "class TranslateBehaviorShadowTableTest"
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/MarshallerTest.php
------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------
 32 | ERROR | Class name doesn't match filename; expected "class MarshallerTest"
------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/ORM/AssociationTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------
 25 | ERROR | Class name doesn't match filename; expected "class AssociationTest"
-------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Event/EventListTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------
 25 | ERROR | Class name doesn't match filename; expected "class EventListTest"
-------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Event/EventManagerTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------
 28 | ERROR | Class name doesn't match filename; expected "class EventManagerTest"
----------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Utility/MergeVariablesTraitTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 21 | ERROR | Class name doesn't match filename; expected "class MergeVariablesTraitTest"
-------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Routing/Route/RouteTest.php
-----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class RouteTest"
-----------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Collection/CollectionTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class CollectionTest"
-------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Mailer/MailerAwareTraitTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------
 24 | ERROR | Class name doesn't match filename; expected "class MailerAwareTraitTest"
---------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Mailer/RendererTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------
 21 | ERROR | Class name doesn't match filename; expected "class RendererTest"
-------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Mailer/Transport/SmtpTransportTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class SmtpTransportTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Mailer/EmailTest.php
----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------
 30 | ERROR | Class name doesn't match filename; expected "class EmailTest"
----------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Auth/DigestAuthenticateTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------
 33 | ERROR | Class name doesn't match filename; expected "class DigestAuthenticateTest"
---------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/TestSuite/TestCaseTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------
 31 | ERROR | Class name doesn't match filename; expected "class TestCaseTest"
----------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/TestSuite/TestFixtureTest.php
-------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------
 29 | ERROR | Class name doesn't match filename; expected "class TestFixtureTest"
-------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/Form/EntityContextTest.php
---------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------------
 32 | ERROR | Class name doesn't match filename; expected "class EntityContextTest"
---------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/StringTemplateTraitTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 25 | ERROR | Class name doesn't match filename; expected "class StringTemplateTraitTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/HelperRegistryTest.php
-----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------
 26 | ERROR | Class name doesn't match filename; expected "class HelperRegistryTest"
-----------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/ViewTest.php
-------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------
 34 | ERROR | Class name doesn't match filename; expected "class ViewTest"
-------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/Widget/WidgetLocatorTest.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 26 | ERROR | Class name doesn't match filename; expected "class WidgetLocatorTest"
-----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/HelperTest.php
---------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------
 26 | ERROR | Class name doesn't match filename; expected "class HelperTest"
---------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/Helper/NumberHelperTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------------
 28 | ERROR | Class name doesn't match filename; expected "class NumberHelperTest"
----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/Helper/TextHelperTest.php
--------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------
 26 | ERROR | Class name doesn't match filename; expected "class TextHelperTest"
--------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/View/Helper/FormHelperTest.php
--------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------
 36 | ERROR | Class name doesn't match filename; expected "class FormHelperTest"
--------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Log/Engine/FileLogTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class FileLogTest"
----------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/TestCase/Log/Engine/BaseLogTest.php
----------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------------------------
 27 | ERROR | Class name doesn't match filename; expected "class BaseLogTest"
----------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/test_app/vendor/sample/configure_test_vendor_sample.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 20 | ERROR | Class name doesn't match filename; expected "class configure_test_vendor_sample"
------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: cakephp/cakephp/tests/test_app/Plugin/TestPlugin/src/Vendor/sample/sample_plugin.php
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 20 | ERROR | Class name doesn't match filename; expected "class sample_plugin"
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ADmad** [comment]
:+1: if you are ready to take up the chore of updating core violations :).

**Comment by dereuromark** [comment]
I already did some, I am sure open to help from others here as well :)

**Comment by ADmad** [comment]
@dereuromark Couldn't we have used the `Squiz.Classes.ClassFileName` sniff instead of having our own sniff class?

**Comment by dereuromark** [comment]
If that serves the same quality purpose, we sure can. 
I am sure, however, that there was a reason why it was not used at the time.

**Comment by ADmad** [comment]
[This](https://github.com/cakephp/cakephp/blob/4.x/tests/TestCase/Utility/MergeVariablesTraitTest.php) for example still has multiple classes declared which the sniff you added doesn't detect while `Squiz.Classes.ClassFileName` did.

**Comment by dereuromark** [comment]
That is on purpose: As only the first class is relevant for it.
This can help in cases where you would want to have an exception to it (below, not above).
If we dont want/need this, and no other obstacles prevent it, we can sure switch.

**Comment by dereuromark** [comment]
Bear in mind that this sniff is not only for core, but for the whole community, as such all restrictions we impose we also impose on all plugins and apps. As such I found the current one a fair compromise.

**Comment by ADmad** [comment]
> That is on purpose: As only the first class is relevant for it.

Why? If we want to ensure one class per file then extra classes shouldn't be allowed below either.

> Bear in mind that this sniff is not only for core, but for the whole community, as such all restrictions we impose we also impose on all plugins and apps.

Actually it is. No one is forced to use this standard in their plugin or apps. Specific sniffs can be overridden.

**Comment by ADmad** [comment]
It's better to use already available sniffs wherever possible instead of adding own and creating maintenance overhead.

**Pull request merged**
