### PR TITLE
fix "Undefined index: type_space [and var_space]"

### PR DESCRIPTION
**Pull request by luke83**

### CODE REVIEW

**Comment by ravage84** [comment]
In what situation does this notice appear? Could you provide some example code or a link?

**Comment by luke83** [comment]
@ravage84 it is not "code example related", it is a logical error: please note line 297 where the variables are defined following *camel case convention*, then they are *compacted* in line 363 using *snake convention* (underscored), but in lines 395 and 397 are accessed using *camel case* instead *underscored* saved in the array.. ironically you get this error when code sniffing tray to suggest you to change variable like ``my_variable`` in ``myVariable``

**Comment by ravage84** [comment]
:+1: A brief explanation and a link like https://github.com/luke83/cakephp-codesniffer/blob/patch-1/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php#L297 in the PR description would have helped. :smirk_cat:

**Comment by luke83** [comment]
@ravage84 you right, but late friday lazy neurons.. -.-'

**Comment by markstory** [comment]
Looks good. I expanded the context and the variables are totally defined as camelBack like @luke83 said.

**Pull request merged**
