### PR TITLE
Make error message for privat variable more clear

### PR DESCRIPTION
**Pull request by xhs345**

### CODE REVIEW

**Comment by dereuromark** [comment]
👍

**Comment by narendravaghela** [comment]
:+1:

**Comment by xhs345** [comment]
Caused me more headache than I'm willing to admit

**Comment by dereuromark** [comment]
You shouldn't ever be using private, especially not with __ prefix.. :)
I sure don't and never have those headaches.

**Comment by thinkingmedia** [comment]
@dereuromark maybe he wasn't using a `__`, but had one by mistake and was lost trying to find it. Since the error said it only had one underscore. 😼

**Comment by xhs345** [comment]
@dereuromark Thanks for the tip, I like that approach

@thinkingmedia Yea, I had private variables and refactored them with one underscore only. Thought it was a PHPStorm error at first

**Pull request merged**
