### PR TITLE
Added the inflector functions inside the  ValidVariableNameSniff

### PR DESCRIPTION
**Pull request by gmponos**
Closes https://github.com/cakephp/cakephp-codesniffer/issues/183

### CODE REVIEW

**Comment by ADmad** [comment]
Having these inflection methods in a separate utility class or trait would be better.

**Comment by gmponos** [comment]
Yes once you move to codesniffer 3,x this can be done. For now I find No reason. I've seen from other Codesniffer packages that having external libs because of the autoloading that codesniffer has it is mixing things in a weird way.

Have in mind that I haven't tested it. Hoping that the tests are passing this will be fine.

**Comment by ADmad** [comment]
Given that we are almost ready to release 3.0.0 (#187) it would be better to make this fix on 3.0 branch itself.

**Comment by gmponos** [comment]
I have a question to make here though. 

Is there a chance people might use the current version without the inflector? 

If they can easily update their cakephp/codesniffer without require updating any other libraries this should be fine and I guess it must be mentioned somewhere as know issue?

**Comment by gmponos** [comment]
Anyway since the linked issue is opened since january and noone has rementioned or bothered with it again maybe you are correct and the chances of this happening are not so big so you shouldn't bother. 

I guess it's your call. Let me know. 😃

**Comment by gmponos** [comment]
Basically according to this [commit](https://github.com/cakephp/cakephp-codesniffer/pull/187/commits/613d64b1406979a88c8cfa45acedc28b89e60d5b) I think it will be even better to remove this sniff from v2.x. or just do a dummy extend of the zend one in order to have be backward compatible.

So I am closing this.

**Comment by ADmad** [comment]
#187 was open since we were waiting for codsniffer v3 stable to be release. That was done few days ago so that PR is now merged and `3.0.0` released.

`ValidVariableNameSniff.php` has been simply removed in 3.0 and instead we just use similar sniffs provided by the Zend standard making this PR obsolete.

**Pull request closed without merging**
